"""added balance

Revision ID: 0c33434b5022
Revises: 6c03ac05f149
Create Date: 2024-05-24 12:02:48.122994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c33434b5022'
down_revision = '6c03ac05f149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index('category')
        batch_op.drop_index('user')
        batch_op.create_foreign_key(None, 'users', ['idU'], ['idU'])
        batch_op.create_foreign_key(None, 'category', ['idC'], ['idC'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('user', ['idU'], unique=False)
        batch_op.create_index('category', ['idC'], unique=False)

    # ### end Alembic commands ###
